// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdSj0qR3IhoCfIUh-EEzSne5hnbnGXtoE',
    appId: '1:16999829693:web:8b6a6eebe7b8a5c1fca7d4',
    messagingSenderId: '16999829693',
    projectId: 'securax-ef2db',
    authDomain: 'securax-ef2db.firebaseapp.com',
    storageBucket: 'securax-ef2db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIL8Txaaya6rqjFTGibi4oX6ISgKMqEK4',
    appId: '1:16999829693:android:53376d5964c19916fca7d4',
    messagingSenderId: '16999829693',
    projectId: 'securax-ef2db',
    storageBucket: 'securax-ef2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKMoJDJ4IISg5-PxDNNT0p6HRZfFeYDxI',
    appId: '1:16999829693:ios:f9dcd2a4749d9467fca7d4',
    messagingSenderId: '16999829693',
    projectId: 'securax-ef2db',
    storageBucket: 'securax-ef2db.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKMoJDJ4IISg5-PxDNNT0p6HRZfFeYDxI',
    appId: '1:16999829693:ios:f9dcd2a4749d9467fca7d4',
    messagingSenderId: '16999829693',
    projectId: 'securax-ef2db',
    storageBucket: 'securax-ef2db.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdSj0qR3IhoCfIUh-EEzSne5hnbnGXtoE',
    appId: '1:16999829693:web:38f96379bde13d6bfca7d4',
    messagingSenderId: '16999829693',
    projectId: 'securax-ef2db',
    authDomain: 'securax-ef2db.firebaseapp.com',
    storageBucket: 'securax-ef2db.firebasestorage.app',
  );
}
